name: Builds and pushes Backend API Docker image
on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend_api.yaml'
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend_api.yaml'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  ctx:
    name: Context
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: vars
        uses: ./.github/actions/context/
        with:
          docker_repository: ghcr.io/imbod/imbod-backend
    outputs:
      docker_image_latest_tag: ${{ steps.vars.outputs.docker_image_latest_tag }}
      docker_image_git_tag: ${{ steps.vars.outputs.docker_image_git_tag }}
      git_commit_sha: ${{ steps.vars.outputs.git_commit_sha }}
      docker_repository: ${{ steps.vars.outputs.docker_repository }}

  build-test:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: [ctx]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run setup-docker action
        uses: ./.github/actions/setup-docker
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to registry
        uses: docker/build-push-action@v6
        with:
          cache-from: |
            type=registry,ref=${{ needs.ctx.outputs.docker_image_latest_tag }}
          cache-to: type=inline
          context: ./services/backend
          platforms: linux/amd64
          push: true
          tags: ${{ needs.ctx.outputs.docker_image_git_tag }},${{ needs.ctx.outputs.docker_image_latest_tag }}
